feat: improve error message
when init config failed:

```
Error: init config failed

Caused by:
    0: internal server error read ./config.toml failed
    1: read ./config.toml failed
    2: No such file or directory (os error 2)
```